from rsf.proj import *

Flow('velmod',None,
	'''
	spike n1=300 d1=0.01 o1=0. n2=1000 d2=0.01 o2=0.
	label1=Depth label2=Distance unit1=Km unit2=Km |
	math output="x1*0.5+1.5"
	''')

Plot('velmod',
	'''
	grey color=j scalebar=y barreverse=y bias=1.5
	title="Velocity"
	''')

Flow('ray','velmod','rays2 zshot=0. yshot=2. nt=5000 dt=0.001 nr=1 a0=135')

Plot('ray',
	'''
	graph plotcol=0 min1=0 max1=3 min2=0 max2=10
	transp=y wanttitle=n wantaxis=n yreverse=y scalebar=y
	symbol=+
	''')

Result('rayplot','velmod ray','Overlay')

End()
